
name: build vault unseal image

on:
  push:
    paths:
      - docker/*

env:
  REGISTRY: quay.io
  IMAGE_NAME: vault-unseal

jobs: 
  build:
    name: Build and push image to quay.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker
          push: true
          tags: quay.io/dystewar/vault-unseal